export enum DocumentType {
  ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT = 'ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT',
  CUSTOM = 'CUSTOM',
  EMANCIPATION_OF_MINORS = 'EMANCIPATION_OF_MINORS',
  ENTREPRENEUR_REQUIREMENT = 'ENTREPRENEUR_REQUIREMENT',
  IDENTIFICATION_SELFIE = 'IDENTIFICATION_SELFIE',
  IDENTIFICATION = 'IDENTIFICATION',
  INVOICE = 'INVOICE',
  MEI_CERTIFICATE = 'MEI_CERTIFICATE',
  MINUTES_OF_CONSTITUTION = 'MINUTES_OF_CONSTITUTION',
  MINUTES_OF_ELECTION = 'MINUTES_OF_ELECTION',
  POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY',
  SOCIAL_CONTRACT = 'SOCIAL_CONTRACT',
}
