export enum NotificationEvent {
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  PAYMENT_DUEDATE_WARNING = 'PAYMENT_DUEDATE_WARNING',
  SEND_LINHA_DIGITAVEL = 'SEND_LINHA_DIGITAVEL',
}
